### Ejercicio: Datos climáticos estación

Crea un nuevo DataFrame con datos de 1 estaciones SENAMHI de diferentes regiones del Perú (https://www.senamhi.gob.pe/site/descarga-datos/).

Considerar lo siguiente a partir de "tutorial-para-la-descarga-de-datos.pdf".

Los datos de las columnas corresponden a:
- Columna A: Año
- Columna B: Mes
- Columna C: Día
- Columna D: Precipitación acumulada
- Columna E: Temperatura máxima
- Columna F: Temperatura mínima

En las celdas donde aparece -99.9 significa que no hay información disponible para esa variable

Luego:
1. Parsear el nombres de la estación Chosica y leer el archivo.
1. Calcula el promedio mensual de precipitación
1. Calcula el promedio anual de precipitación
2. Identifica el día más lluvioso
4. Exporta los resultados formateados en CSV

In [5]:
# Tu código aquí – Ejercicio: Estación

# Leer los datos de las estaciones y crear un DataFrame combinado
import os
files = os.listdir('/content/drive/MyDrive/archivosprueba')  # Lista los archivos en el directorio
files

['Copia de qc00000543_ñaña.txt',
 'Copia de qc00151205_CANCHACALLA.txt',
 'Copia de qc00151209_chosica.txt',
 'Copia de qc00155213_santa_eulalia.txt',
 'Copia de qc00155224_santiago_de_tuna.txt']

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
from os.path import split
# Parsear el nombre del archivo para obtener el código y nombre de la estación
station = files[4]

ruta, archivo = split(station)

archivo = archivo.replace("Copia de ", "").replace(".txt", "")

codigo, nombre = archivo.split("_", 1)

print(f"Código: {codigo}, Nombre: {nombre}")

Código: qc00155224, Nombre: santiago_de_tuna

In [16]:
# Leer el archivo CSV de la estación seleccionada
import pandas as pd

station_df = pd.read_table(
    f'/content/drive/MyDrive/archivosprueba/{station}',
    header=None,
    sep=r'\s+',
    na_values=['-999', '-99.9']
)

station_df.head()

# clima_df.columns = ['Año', 'Mes', 'Dia', 'Pr','Tmax', 'Tmin']  # Asignar nombres de columnas
station_df.columns = ['Año', 'Mes', 'Dia', 'Pr', 'Tmax', 'Tmin']

station_df.head()
station_df.head(10)

    Año  Mes  Dia  Pr  Tmax  Tmin
0  1963   12    1 NaN   NaN   NaN
1  1963   12    2 NaN   NaN   NaN
2  1963   12    3 NaN   NaN   NaN
3  1963   12    4 NaN   NaN   NaN
4  1963   12    5 NaN   NaN   NaN
5  1963   12    6 NaN   NaN   NaN
6  1963   12    7 NaN   NaN   NaN
7  1963   12    8 NaN   NaN   NaN
8  1963   12    9 NaN   NaN   NaN
9  1963   12   10 NaN   NaN   NaN

In [17]:
station_df['Año'] = station_df['Año'].astype(int)
station_df['Mes'] = station_df['Mes'].astype(int)
station_df['Dia'] = station_df['Dia'].astype(int)

station_df['Pr'] = pd.to_numeric(station_df['Pr'], errors='coerce')
station_df['Tmax'] = pd.to_numeric(station_df['Tmax'], errors='coerce')
station_df['Tmin'] = pd.to_numeric(station_df['Tmin'], errors='coerce')


# Precipitación mensual
precipitacion_mensual = station_df.groupby(
    ['Año', 'Mes']
)['Pr'].sum()


# Precipitación total anual
precipitacion_anual = station_df.groupby(
    'Año'
)['Pr'].sum()


# Día más lluvioso
dia_mas_lluvioso = station_df.loc[
    station_df['Pr'].idxmax()
]


print(f"Precipitación mensual:\n{precipitacion_mensual}\n")

print(f"Precipitación anual:\n{precipitacion_anual}\n")

print(
    f"El día más lluvioso fue el "
    f"{dia_mas_lluvioso['Año']:.0f}-"
    f"{dia_mas_lluvioso['Mes']:.0f}-"
    f"{dia_mas_lluvioso['Dia']:.0f} "
    f"con {dia_mas_lluvioso['Pr']} mm de precipitación."
)

Precipitación mensual:
Año   Mes
1963  12      0.0
1964  1       7.0
      2      26.6
      3      16.5
      4      24.0
             ...
2013  9       0.0
      10      0.0
      11      4.1
      12      1.5
2014  1      39.8
Name: Pr, Length: 602, dtype: float64

Precipitación anual:
Año
1963      0.0
1964     99.4
1965    138.5
1966    197.0
1967    614.3
1968     65.1
1969    270.6
1970    347.7
1971    282.6
1972    477.0
1973    304.2
1974    298.0
1975    227.5
1976    259.3
1977    420.8
1978    146.7
1979    174.6
1980    131.0
1981    385.9
1982    377.0
1983    600.2
1984    726.1
1985    274.7
1986    632.0
1987    257.6
1988    311.8
1989    707.2
1990    219.3
1991    283.1
1992     22.1
1993    407.2
1994    289.7
1995    212.7
1996    268.5
1997    218.2
1998    456.3
1999    300.3
2000    354.0
2001    344.1
2002    314.1
2003    197.4
2004    196.8
2005    129.6
2006    340.2
2007    266.2
2008    444.0
2009    463.2
2010    114.5
2011    222.1
2012    286.7
2013    194.9
2014     39.8
Name: Pr, dtype: float64

El día más lluvioso fue el 1970-1-15 con 89.9 mm de precipitación.

### Ejercicio 2: Datos climáticos multiestación

Crea un nuevo DataFrame con datos de 5 estaciones SENAMHI de diferentes regiones del Perú (https://www.senamhi.gob.pe/site/descarga-datos/).

Luego:
1. Paresear el nombres de la estaciones y leer los archivo.
1. Unir las db (Fecha, Est1, Est2, ...)
1. Calcula el promedio mensual de precipitación por región
2. Identifica el mes más lluvioso en cada estación
4. Exporta el resultado formateado a CSV

In [31]:


import os
import pandas as pd
from os.path import split

# Ruta
ruta = '/content/drive/MyDrive/Colab Notebooks/Ciencia de datos ambientales/estaciones'

# Lista de archivos
files = os.listdir(ruta)

# Diccionario para guardar los DataFrames
estaciones = {}

# 1. Parsear el nombre de las estaciones y leer los archivos

for station in files:

    # Separar el nombre del archivo usando split
    _, archivo = split(station)

    # Quitar "Copia de " y ".txt"
    archivo = archivo.replace(".txt", "")

    # Separar código y nombre de estación
    codigo, nombre = archivo.split("_", 1)

    print(f"Código: {codigo}, Nombre: {nombre}")

    # Leer archivo
    station_df = pd.read_table(
        f'{ruta}/{station}',
        header=None,
        sep=r'\s+',
        na_values=['-999', '-99.9']
    )

    # Las 6 columnas
    station_df.columns = ['year', 'month', 'day', 'Pr', 'Tmax', 'Tmin']


    station_df['year'] = station_df['year'].astype(int)
    station_df['month'] = station_df['month'].astype(int)
    station_df['day'] = station_df['day'].astype(int)
    station_df['Pr'] = pd.to_numeric(station_df['Pr'], errors='coerce')
    station_df['Tmax'] = pd.to_numeric(station_df['Tmax'], errors='coerce')
    station_df['Tmin'] = pd.to_numeric(station_df['Tmin'], errors='coerce')

    station_df['Fecha'] = pd.to_datetime(
    station_df[['year', 'month', 'day']])
    estaciones[nombre] = station_df[['Fecha', 'Pr']]

Código: qc00154101, Nombre: callancas
Código: qc00154106, Nombre: huacamarcanga
Código: qc00154111, Nombre: sinsacap
Código: qc00153206, Nombre: julcan
Código: qc00154112, Nombre: huangacocha

In [32]:
station_df.head(10)

   year  month  day    Pr  Tmax  Tmin      Fecha
0  1971      6    1   0.0   NaN   NaN 1971-06-01
1  1971      6    2   0.0   NaN   NaN 1971-06-02
2  1971      6    3   0.0   NaN   NaN 1971-06-03
3  1971      6    4   4.0   NaN   NaN 1971-06-04
4  1971      6    5   0.0   NaN   NaN 1971-06-05
5  1971      6    6   3.0   NaN   NaN 1971-06-06
6  1971      6    7   0.0   NaN   NaN 1971-06-07
7  1971      6    8   2.0   NaN   NaN 1971-06-08
8  1971      6    9   1.0   NaN   NaN 1971-06-09
9  1971      6   10  22.0   NaN   NaN 1971-06-10

In [34]:
# Crear la base combinada
db_final = None

for nombre, df in estaciones.items():

    df = df.rename(columns={'Pr': nombre})

    if db_final is None:
        db_final = df
    else:
        db_final = pd.merge(
            db_final,
            df,
            on='Fecha',
            how='outer'
        )

db_final  = db_final.sort_values('Fecha')

print(db_final.head())

       Fecha  callancas  huacamarcanga  sinsacap  julcan  huangacocha
0 1963-09-01        0.0            0.0       NaN     0.0          NaN
1 1963-09-02        0.0            0.0       NaN     0.0          NaN
2 1963-09-03        0.0            0.0       NaN     0.0          NaN
3 1963-09-04        0.0            0.0       NaN     0.0          NaN
4 1963-09-05        0.0            0.0       NaN     0.0          NaN

In [35]:
# Crear año y mes
db_final['Año'] = db_final['Fecha'].dt.year
db_final['Mes'] = db_final['Fecha'].dt.month

# Nombres de las estaciones
nombres_estaciones = list(estaciones.keys())

# Promedio mensual
precipitacion_mensual = db_final.groupby(
    ['Año', 'Mes']
)[nombres_estaciones].mean()

print(precipitacion_mensual)

          callancas  huacamarcanga  sinsacap    julcan  huangacocha
Año  Mes
1963 9     0.466667       0.110000       NaN  0.000000          NaN
     10    2.567742       1.361613       NaN  0.487097          NaN
     11    4.526667       1.880667  3.253333  0.886667          NaN
     12    4.512903       2.123548  3.606452  0.477419          NaN
1964 1     4.564516       1.284839  3.193548  1.383871          NaN
...             ...            ...       ...       ...          ...
2014 3          NaN            NaN  7.958065       NaN          NaN
     4          NaN            NaN  2.790000       NaN          NaN
     5          NaN            NaN  2.216129       NaN          NaN
     6          NaN            NaN  0.240000       NaN          NaN
     7          NaN            NaN  0.058065       NaN          NaN

[611 rows x 5 columns]

In [36]:
# Promedio de precipitación para cada mes
promedio_por_mes = db_final.groupby(
    'Mes'
)[nombres_estaciones].mean()

# Mes con mayor precipitación
mes_mas_lluvioso = promedio_por_mes.idxmax()

# Precipitación correspondiente
precipitacion_maxima = promedio_por_mes.max()

for estacion in nombres_estaciones:
    print(
        f"{estacion}: mes {mes_mas_lluvioso[estacion]} "
        f"({precipitacion_maxima[estacion]:.2f} mm)"
    )

callancas: mes 3 (6.66 mm)
huacamarcanga: mes 3 (4.51 mm)
sinsacap: mes 3 (5.21 mm)
julcan: mes 3 (3.88 mm)
huangacocha: mes 3 (6.44 mm)

In [37]:
db_final.to_csv(
    f'{ruta}/estaciones_combinadas.csv',
    index=False
)